---
apiVersion: skaffold/v4beta1
kind: Config
build:
  artifacts:
  - image: registry.baidubce.com/csm/pixie-dev/src/e2e_test/vzconn_loadtest/server_image
    context: .
    bazel:
      target: //src/e2e_test/vzconn_loadtest:server_image.tar
  tagPolicy:
    dateTime: {}
manifests:
  kustomize:
    paths:
    - src/e2e_test/vzconn_loadtest/k8s
